resources:
- templates/disallow-latest.yaml
- templates/require-owner.yaml
- templates/require-limits.yaml

- constraints/disallow-latest.yaml
- constraints/require-owner.yaml
- constraints/require-limits.yaml