apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
  namespace: demo
rules:
- apiGroups: ["", "apps", "argoproj.io"]
  resources: ["pods", "services", "deployments", "rollouts"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: viewer
  namespace: demo
rules:
- apiGroups: ["", "apps", "argoproj.io"]
  resources: ["pods", "services", "deployments", "rollouts"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sre
rules:
- apiGroups: ["", "apps", "argoproj.io"]
  resources: ["pods", "services", "deployments", "rollouts", "namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-developer
  namespace: demo
subjects:
- kind: User
  name: developer
roleRef:
  kind: Role
  name: developer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-viewer
  namespace: demo
subjects:
- kind: User
  name: viewer
roleRef:
  kind: Role
  name: viewer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-sre
subjects:
- kind: User
  name: sre
roleRef:
  kind: ClusterRole
  name: sre
  apiGroup: rbac.authorization.k8s.io