name: Build Scan Sign

on:
  push:
    branches:
    - main

jobs:
  build-scan-sign:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    env:
      IMAGE: ghcr.io/tieuphuong1711/w10-api:${{ github.sha }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build image
      run: |
        docker build -t $IMAGE ./src/api

    - name: Trivy scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.IMAGE }}
        severity: HIGH,CRITICAL
        exit-code: 1

    - name: Push image
      run: |
        docker push $IMAGE

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3

    - name: Cosign sign image
      run: |
        cosign sign --yes $IMAGE